### ISSUE TITLE
Make headers configurable

### ISSUE THREAD

**Issue by afternoon** [nabil-boag/angular-multimocks#10]
MIME type is hard-coded:

https://github.com/wongatech/angular-multimocks/blob/master/app/src/js/multimocks.js#L42

This should be configurable through the provider API. As a nice-to-have, we should make all headers configurable.

**Comment by edconolly** [comment]
The change needs to happen here
https://github.com/wongatech/angular-multimocks/blob/master/app/src/js/multimocks.js#L42

The multimocksdata provider needs to be expanded to take some header information so that we can remove the hardcoded reference to HAL
