### ISSUE TITLE
Provide demo app

### ISSUE THREAD

**Issue by edconolly** [nabil-boag/angular-multimocks#11]
It's currently difficult to see how everything fits together, and there's no way to develop a check my changes without bringing into another project.

**Comment by afternoon** [comment]
A demo project with a Gruntfile, mock resource files and a couple of E2E tests which load different scenarios would be great.

**Comment by afternoon** [comment]
Demo app PR has been merged. I'm dropping the E2E tests requirement. We'll test the grunt task instead.
