### ISSUE TITLE
grunt workflow:dev should open the demo app

### ISSUE THREAD

**Issue by afternoon** [nabil-boag/angular-multimocks#15]
Open the demo app currently:

``` sh
cd demo
grunt
open http://localhost:9000/
```

**Comment by nabil-boag** [comment]
A pull request resolving your request is waiting review: 

https://github.com/wongatech/angular-multimocks/pull/26

**Comment by nabil-boag** [comment]
@afternoon Can you please test/close this issue.

Thanks

**Comment by afternoon** [comment]
Tested! Works!
