### ISSUE TITLE
Easily disable API delayed responses

### ISSUE THREAD

**Issue by edconolly** [nabil-boag/angular-multimocks#25]
It's great being about to include API delays to get a feel for the app in the real world, but it's also a pain disabling them come test time. Why don't we have something that makes it easy to ignore the delayed responses. Either turn `responseDelay` into a provider and allow some configuration, or grab something from the URL perhaps `/cart?scenario=emptyCart&responseDelay=false`

**Comment by nabil-boag** [comment]
Hey @edconolly, this is really surprising, I didn't expect this feature to be used in this way. I originally added it so we could write E2E tests for code that has complicated UX around HTTP delays.

**Comment by nabil-boag** [comment]
Hey @edconolly. This feature has now been implemented. It is documented here:

https://github.com/wongatech/angular-multimocks#global-delay-override. 

Are you happy to close this request?

**Comment by edconolly** [comment]
this is awesome!
