### ISSUE TITLE
Make multimocks work with lodash v3

### ISSUE THREAD

**Issue by edconolly** [nabil-boag/angular-multimocks#36]
We have a requirement to use lodash v3, given the new dist folder structure for lodash this will currently break multimocks.

Instead of including 

```
node_modules/lodash/lodash.js
```

We'll have to figure out a way to bundle our own, or list the files projects need to bring in.

**Comment by edconolly** [comment]
or even better kill the lodash dependency? would be worth looking at where we use it perhaps.

**Comment by nabil-boag** [comment]
Great idea @edconolly, removal of lodash: https://github.com/wongatech/angular-multimocks/pull/37

**Comment by nabil-boag** [comment]
@edconolly There is now no lodash dependency. Can you close your issue?

**Comment by nabil-boag** [comment]
Multimocks now works with lodash v3
