### ISSUE TITLE
Move the Scenario menu component into tempo-scenario

### ISSUE THREAD

**Issue by bnppl** [nabil-boag/angular-multimocks#4]
It would be great if the functionality here 
https://github.com/QuickbridgeLtd/ivy/tree/master/app/src/scenarioMenu

Could be made more generic and introduced to this component so that we can get a scenario switcher out of the box on new projects.

**Comment by afternoon** [comment]
I think it makes sense to move some of the menu code into `tempo-scenario`. There are a few bits: generating the list of available scenarios, displaying a page, linking to that page. I'd prefer to keep the UI bits to a minimum, since they're specific to Ivy.

**Comment by afternoon** [comment]
To be clear, I'll definitely take a pull request for this.
