### ISSUE TITLE
Gulp File

### ISSUE THREAD

**Issue by omer72** [nabil-boag/angular-multimocks#43]
Can we use multimocks with Gulpfile?

**Comment by nabil-boag** [comment]
At the moment we don't support Gulp runner. But you should be able to use [gulp-grunt](https://www.npmjs.com/package/gulp-grunt) to import the tasks to generate mocks.

If you are up for a challenge please feel free to implement the existing tasks in a way that supports Gulp!

**Comment by chrisiconolly** [comment]
This has now been added with https://github.com/wongatech/angular-multimocks/commit/92c4e36e63aea9bf5c926f242708b716ae701132.

Use latest version of multimocks (v0.6.8 +) for gulp task
