### ISSUE TITLE
Grunt task should take config option to enable HAL-specific functionality

### ISSUE THREAD

**Issue by afternoon** [nabil-boag/angular-multimocks#9]
The Grunt task currently assumes your API follows HAL patterns. This functionality is useful, but not appropriate to many projects.

The actual scenario data loader operates on URIs, not links, so shouldn't need any modification.
- [x] Don't call `scenarioDataWithLinks` if not a HAL project
- [x] [tasks/writeMultimocks.js#L22](https://github.com/wongatech/angular-multimocks/blob/master/tasks/writeMultimocks.js#L22): Use `uri` instead of `rel`
- [x] [tasks/writeMultimocks.js#L37](https://github.com/wongatech/angular-multimocks/blob/master/tasks/writeMultimocks.js#L37): Don't set `uri` if not a HAL project
- [ ] Use non-HAL examples in README

**Comment by edconolly** [comment]
From https://github.com/wongatech/angular-multimocks/blob/master/tasks/writeMultimocks.js#L84 downwards there's a few methods performing HAL specific functionality.

**Comment by afternoon** [comment]
`scenarioDataWithLinks` is unnecessary if you're not using HAL, so it should be the default to switch that off.

Anything which depends on or uses `rel` should be switched off as well.

We should write tests for the Grunt task with HAL turned on and off.

**Comment by afternoon** [comment]
- tasks/writeMultimocks.js#L22: Use `uri` instead of `rel`.
- tasks/writeMultimocks.js#L37: Don't set `uri` if not a HAL project.
